# Generated by Django 3.2.5 on 2021-11-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experienceLevel',
            field=models.CharField(choices=[('Expert', 'Expert'), ('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Beginer', 'Beginer')], default='BEGINER', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='personalStatement',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
