# Generated by Django 3.2.5 on 2021-12-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_user_experiencelevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_applicant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_officer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='user',
            name='clubs',
            field=models.ManyToManyField(to='clubs.Club'),
        ),
    ]
