# Generated by Django 3.2.5 on 2021-12-14 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20211214_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club_owner',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clubs',
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(related_name='_clubs_club_members_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='officers',
            field=models.ManyToManyField(related_name='_clubs_club_officers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
