# Generated by Django 3.2.5 on 2021-12-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20211214_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferredClub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club'),
        ),
    ]
