# Generated by Django 3.2.5 on 2021-12-15 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_user_preferredclub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(related_name='member_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='officers',
            field=models.ManyToManyField(related_name='officer_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
