# Generated by Django 3.2.5 on 2021-12-16 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_club_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='applicants',
            field=models.ManyToManyField(related_name='applicants_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
